name: Deploy GAS

on:
  push:
    branches:
      - main
    paths:
      - 'gas/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./gas
        run: npm install

      - name: Install clasp
        run: npm install -g @google/clasp@2.4.2

      - name: Create .clasp.json
        working-directory: ./gas
        run: |
          echo "{\"scriptId\":\"$GAS_PROJECT_ID\",\"rootDir\":\"./\"}" > ./.clasp.json
        env:
          GAS_PROJECT_ID: ${{ secrets.GAS_PROJECT_ID }}

      - name: Create .clasprc.json
        run: |
          echo '${{ secrets.GAS_CLASP_TOKEN }}' > ~/.clasprc.json
          chmod 600 ~/.clasprc.json

      - name: Publish
        working-directory: ./gas
        run: |
          clasp push --force

      - name: Get running version
        working-directory: ./gas
        run: |
          echo RUNNING_VERSION="$( clasp deployments | tail -n 1 | awk -F ' ' '{print $3}' )" >> $GITHUB_ENV

      - name: Deploy (Only first time)
        working-directory: ./gas
        if: env.RUNNING_VERSION == '@HEAD'
        run: |
          clasp deploy -d ${GITHUB_SHA:0:7}

      - name: Deploy
        working-directory: ./gas
        if: env.RUNNING_VERSION != '@HEAD'
        run: |
          DEPLOY_ID=$( clasp deployments | tail -n 1 | awk -F ' ' '{print $2}' )
          clasp deploy -d ${GITHUB_SHA:0:7} -i ${DEPLOY_ID}
